executable = /data/user/wkammeem/CORSIKA/submit_ZenithRun.py
arguments = --particle $(p) --energy $(e) --zenith $(z) 
#mkdir -p /scratch/wkammeem/logs
#output = /scratch/wkammeem/logs/job.$(Cluster).$(Process).out
#error  = /scratch/wkammeem/logs/job.$(Cluster).$(Process).err
#log    = /scratch/wkammeem/logs/job.$(Cluster).log

#transfer_input_files    = /data/user/wkammeem/CORSIKA/ZenithAngle/
log    = /scratch/wkammeem/log.$(ClusterId).log
error  = /scratch/wkammeem/error.$(ClusterId).err
output = /data/user/wkammeem/CORSIKA/logs/output.$(ClusterId).out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

notification = never

request_cpus = 1
request_memory = 5GB 
request_disk = 1GB
#request_gpus = 1
queue p, e, z from params.txt

