executable = /data/user/wkammeem/CORSIKA/run_corsika.sh
arguments = $(particle) $(energy) $(zenith)
#mkdir -p /scratch/wkammeem/logs
#output = /scratch/wkammeem/logs/job.$(Cluster).$(Process).out
#error  = /scratch/wkammeem/logs/job.$(Cluster).$(Process).err
#log    = /scratch/wkammeem/logs/job.$(Cluster).log

transfer_input_files = corsikaReader.cpp, Makefile, cnpy/, params.txt
log    = /scratch/wkammeem/log.$(ClusterId).log
error  = /scratch/wkammeem/error.$(ClusterId).err
output = /data/user/wkammeem/CORSIKA/logs/output.$(ClusterId).out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

notification = never
# transfer_input_files = physics.py

request_cpus = 1
request_memory = 4GB 
request_disk = 2GB
#request_gpus = 1
queue particle, energy, zenith from params_all.txt

