executable = /data/user/wkammeem/CORSIKA/submit_RadiationEnergyPlot.py
arguments = --particle $(p) --energy $(e)

transfer_input_files    = /data/user/wkammeem/CORSIKA/Xmax, /data/user/wkammeem/CORSIKA/radEnergy/norm_sintheta2, /data/user/wkammeem/CORSIKA/radEnergy/raw

log    = /scratch/wkammeem/log.$(ClusterId).log
error  = /scratch/wkammeem/error.$(ClusterId).err
output = /data/user/wkammeem/CORSIKA/logs/output.$(ClusterId).out
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

notification = never

request_cpus = 1
request_memory = 4GB 
request_disk = 2GB
#request_gpus = 1
queue p, e from params.txt

